# Generated by Django 4.2.5 on 2023-10-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "st_id",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Магазин",
                    ),
                ),
                ("st_city_id", models.CharField(max_length=150, verbose_name="Город")),
                (
                    "st_division_code",
                    models.CharField(max_length=150, verbose_name="Дивизион"),
                ),
                (
                    "st_type_format_id",
                    models.IntegerField(verbose_name="Формат магазина"),
                ),
                ("st_type_loc_id", models.IntegerField(verbose_name="Тип локации")),
                (
                    "st_type_size_id",
                    models.IntegerField(verbose_name="Размер магазина"),
                ),
                ("st_is_active", models.BooleanField(verbose_name="Флаг активности")),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "pr_sku_id",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Товар",
                    ),
                ),
                (
                    "pr_group_id",
                    models.CharField(max_length=150, verbose_name="Группа товара"),
                ),
                (
                    "pr_cat_id",
                    models.CharField(max_length=150, verbose_name="Категория товара"),
                ),
                (
                    "pr_subcat_id",
                    models.CharField(
                        max_length=150, verbose_name="Подкатегория товара"
                    ),
                ),
                ("pr_uom_id", models.IntegerField(verbose_name="Единицы измерения")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата продаж")),
                (
                    "pr_sales_type_id",
                    models.IntegerField(verbose_name="Флаг наличия промо"),
                ),
                (
                    "pr_sales_in_units",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        verbose_name="Число проданных товаров без промо",
                    ),
                ),
                (
                    "pr_promo_sales_in_units",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        verbose_name="Число проданных товаров c промо",
                    ),
                ),
                (
                    "pr_sales_in_rub",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=8,
                        verbose_name="Продажи без промо в руб",
                    ),
                ),
                (
                    "pr_promo_sales_in_rub",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=8,
                        verbose_name="Продажи c промо в руб",
                    ),
                ),
                (
                    "pr_sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_sku",
                        to="sales.sku",
                        verbose_name="товар",
                    ),
                ),
                (
                    "st_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_store",
                        to="sales.shop",
                        verbose_name="магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажи",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("target", models.IntegerField(verbose_name="Спрос в шт")),
                (
                    "pr_sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_forecast",
                        to="sales.sku",
                        verbose_name="товар",
                    ),
                ),
                (
                    "st_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_forecast",
                        to="sales.shop",
                        verbose_name="магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз",
                "verbose_name_plural": "Прогнозы",
            },
        ),
    ]
